services:
  moderate-harvest:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    container_name: "moderate-harvest"
  mysql: 
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "moderate-harvest"
    volumes:
      - "moderate-harvest-data:/var/lib/mysql"
    container_name: "mysql"
volumes:
  moderate-harvest-data:

